Addr: 8000
SystemOption:
  AccessKey: ""
  SecretKey: ""
  Debug: false
  LogFile: ""
  ProxyURL: ""
# 卖配置
SellOption:
  # 是否持续追盈 ,如果开启了，那么如果已经盈利了会继续增加
  # 止盈/止损点数
  EnableTrailingTakeProfit: false
  # 强制止损点, 达到这个点直接卖掉
  ForceStopLoss: 3
  # 每间隔这个时间去查询一次价格,根据价格的波动指定出售的策略
  Interval: 1000000000
  # 止损点, 如果达到了这个点，则可能会卖掉，如果没有配置 StopLossDuration 则会直接卖掉，
  # 在配置了 StopLossDuration 的前提下，会等待这么多时间，如果在这段时间内还没有涨上去，则会卖掉
  StopLoss: 1.5
  StopLossDuration: 0
  # 止盈点.
  TakeProfit: 2
  # 增加止盈的点数( 已经达到止盈点的前提下 )
  TrailingStopLoss: 0
  # 增加止损的点数 ( 已经达到止盈点的前提下 )
  TrailingTakeProfit: 0
# 买币配置
BuyOption:
  # 已经买入的币种文件 落地存储
  BoughtFile: trade.json
  # 每间隔这个时间去查询一次价格,根据价格的波动指定购买的策略
  Interval: 1
  # 法币
  MainCoin: USDT
  # 最大购买的订单数量
  MaxBuy: 4
  # 每笔订单购买的金额
  MoneyPerOrder: 11
  # 在时间间隔内上涨了多少幅度 就买币
  PriceUpChange: 1
  # 针对已经出售的币种，下次至少间隔多少时间才会继续买入
  SameCoinBlockDuration: 60000000000
  # 白名单，只有在里面出现的币种才会买入
  WhiteList:
    - DOGE
    - BTC
    - ETH
    - BNB
    - BCC
    - NEO
    - LTC
    - QTUM
    - ADA
    - XRP
    - EOS
    - TUSD
    - IOTA
    - XLM
    - ONT
    - TRX
    - ETC
    - ICX
    - VEN
    - NULS
    - VET
    - PAX
    - BCHABC
    - BCHSV
    - USDC
    - LINK
    - WAVES
    - BTT
    - USDS
    - ONG
    - HOT
    - ZIL
    - ZRX
    - FET
    - BAT
    - XMR
    - ZEC
    - IOST
    - CELR
    - DASH
    - NANO
    - OMG
    - THETA
    - ENJ
    - MITH
    - MATIC
    - ATOM
    - TFUEL
    - ONE
    - FTM
    - ALGO
    - USDSB
    - GTO
    - ERD
    - DUSK
    - ANKR
    - WIN
    - COS
    - NPXS
    - COCOS
    - MTL
    - TOMO
    - PERL
    - DENT
    - MFT
    - KEY
    - STORM
    - DOCK
    - WAN
    - FUN
    - CVC
    - CHZ
    - BAND
    - BUSD
    - BEAM
    - XTZ
    - REN
    - RVN
    - HC
    - HBAR
    - NKN
    - STX
    - KAVA
    - ARPA
    - IOTX
    - RLC
    - MCO
    - CTXC
    - BCH
    - TROY
    - VITE
    - FTT
    - EUR
    - OGN
    - DREP
    - BULL
    - BEAR
    - ETHBULL
    - ETHBEAR
    - TCT
    - WRX
    - BTS
    - LSK
    - BNT
    - LTO
    - EOSBULL
    - EOSBEAR
    - XRPBULL
    - XRPBEAR
    - STRAT
    - AION
    - MBL
    - COTI
    - BNBBULL
    - BNBBEAR
    - STPT
    - WTC
    - DATA
    - XZC
    - SOL
    - CTSI
    - HIVE
    - CHR
    - BTCUP
    - BTCDOWN
    - GXS
    - ARDR
    - LEND
    - MDT
    - STMX
    - KNC
    - REP
    - LRC
    - PNT
    - COMP
    - BKRW
    - SC
    - ZEN
    - SNX
    - ETHUP
    - ETHDOWN
    - ADAUP
    - ADADOWN
    - LINKUP
    - LINKDOWN
    - VTHO
    - DGB
    - GBP
    - SXP
    - MKR
    - DAI
    - DCR
    - STORJ
    - BNBUP
    - BNBDOWN
    - XTZUP
    - XTZDOWN
    - MANA
    - AUD
    - YFI
    - BAL
    - BLZ
    - IRIS
    - KMD
    - JST
    - SRM
    - ANT
    - CRV
    - SAND
    - OCEAN
    - NMR
    - DOT
    - LUNA
    - RSR
    - PAXG
    - WNXM
    - TRB
    - BZRX
    - SUSHI
    - YFII
    - KSM
    - EGLD
    - DIA
    - RUNE
    - FIO
    - UMA
    - EOSUP
    - EOSDOWN
    - TRXUP
    - TRXDOWN
    - XRPUP
    - XRPDOWN
    - DOTUP
    - DOTDOWN
    - BEL
    - WING
    - LTCUP
    - LTCDOWN
    - UNI
    - NBS
    - OXT
    - SUN
    - AVAX
    - HNT
    - FLM
    - UNIUP
    - UNIDOWN
    - ORN
    - UTK
    - XVS
    - ALPHA
    - AAVE
    - NEAR
    - SXPUP
    - SXPDOWN
    - FIL
    - FILUP
    - FILDOWN
    - YFIUP
    - YFIDOWN
    - INJ
    - AUDIO
    - CTK
    - BCHUP
    - BCHDOWN
    - AKRO
    - AXS
    - HARD
    - DNT
    - STRAX
    - UNFI
    - ROSE
    - AVA
    - XEM
    - AAVEUP
    - AAVEDOWN
    - SKL
    - SUSD
    - SUSHIUP
    - SUSHIDOWN
    - XLMUP
    - XLMDOWN
    - GRT
    - JUV
    - PSG
    - 1INCH
    - REEF
    - OG
    - ATM
    - ASR
    - CELO
    - RIF
    - BTCST
    - TRU
    - CKB
    - TWT
    - FIRO
    - LIT
    - SFP
    - DODO
    - CAKE
    - ACM
    - BADGER
    - FIS
    - OM
    - POND
    - DEGO
    - ALICE
    - LINA
    - PERP
    - RAMP
    - SUPER
    - CFX
    - EPS
    - AUTO
    - TKO
    - PUNDIX
    - TLM
    - 1INCHUP
    - 1INCHDOWN
    - BTG
    - MIR
    - BAR
    - FORTH
    - BAKE
    - BURGER
    - SLP
